{
  "os": "linux",
  "dist": "trusty",
  "sudo": "required",
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "node_js": "10",
  "cache": "yarn",
  "language": "node_js",
  "script": [
    "yarn workspaces run lint",
    "yarn workspaces run test"
  ],
  "before_install": [
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",
    "sleep 3",
    "npm install -g yarn@1.21.1"
  ]
}
