{
  "os": "linux",
  "dist": "trusty",
  "sudo": "required",
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "addons": {
    "apt": {
      "sources": [
        "google-chrome"
      ],
      "packages": [
        "google-chrome-stable"
      ]
    }
  },
  "node_js": "8",
  "language": "node_js",
  "after_script": [
    "npm run install",
    "npm run lint",
    "npm run test",
    "npm run test-in"
  ],
  "before_install": [
    "export DISPLAY=:99.0",
    "sh -e /etc/init.d/xvfb start",
    "sleep 3"
  ]
}