service: graphql

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  memorySize: 512
  versionFunctions: false

plugins:
  - serverless-domain-manager

functions:
  graphql:
    handler: handler.graphqlHandler
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    events:
    - http:
        path: graphql
        method: post
        cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Isssr
            allowCredentials: true

custom:
  customDomain:
    domainName: api.manuelvilling.de
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
